# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('cafe_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID кафе')),
                ('cafe_description', models.CharField(max_length=1000, verbose_name='Описание кафе')),
                ('cafe_rating', models.FloatField(verbose_name='Рэйтинг кафе')),
                ('cafe_opening_hours', models.DateTimeField(verbose_name='Часы работы кафе')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('coordinates_id', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon', models.FloatField(verbose_name='Долгота')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False)),
                ('icon', models.CharField(max_length=1000, verbose_name='Иконка кафе')),
                ('photos', models.CharField(max_length=1000, verbose_name='Картинки кафе')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID владельца')),
                ('owner_name', models.CharField(max_length=1000, verbose_name='ФИО владельца')),
                ('owner_phone_number', models.TextField(verbose_name='Телефон владельца')),
                ('owner_email', models.TextField(verbose_name='Email владельца')),
            ],
        ),
        migrations.AddField(
            model_name='cafe',
            name='cafe_coordinates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafes.Coordinates', verbose_name='Координаты кафе'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='cafe_media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafes.Media', verbose_name='Фогографии кафе'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='cafe_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafes.Owner', verbose_name='Владелец кафе'),
        ),
    ]
