# Generated by Django 2.0.6 on 2018-06-30 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('cafe_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID кафе')),
                ('cafe_name', models.CharField(default=' ', max_length=1000, verbose_name='Название кафе')),
                ('cafe_description', models.CharField(max_length=1000, verbose_name='Описание кафе')),
                ('cafe_rating', models.FloatField(verbose_name='Рейтинг кафе')),
            ],
        ),
        migrations.CreateModel(
            name='CafeMedia',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False)),
                ('icon', models.ImageField(upload_to='', verbose_name='Иконка кафе')),
                ('photos', models.ImageField(upload_to='', verbose_name='Картинки кафе')),
                ('cafe_id', models.IntegerField(verbose_name='ID кафе')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('coordinates_id', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon', models.FloatField(verbose_name='Долгота')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=1000, verbose_name='Название элемента')),
                ('item_description', models.TextField(verbose_name='Описание элемента')),
                ('item_icon', models.ImageField(upload_to='', verbose_name='Иконка элемента')),
                ('item_image', models.ImageField(upload_to='', verbose_name='Фото элемента')),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('opening_hours_id', models.AutoField(primary_key=True, serialize=False)),
                ('opening_time', models.TimeField(verbose_name='Время открытия')),
                ('closing_time', models.TimeField(verbose_name='Время закрытия')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID владельца')),
                ('owner_name', models.CharField(max_length=1000, verbose_name='ФИО владельца')),
                ('owner_phone_number', models.TextField(verbose_name='Телефон владельца')),
                ('owner_email', models.TextField(verbose_name='Email владельца')),
            ],
        ),
        migrations.AddField(
            model_name='cafe',
            name='cafe_coordinates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafes.Coordinates', verbose_name='Координаты кафе'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='cafe_menu',
            field=models.ManyToManyField(to='cafes.Item'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='cafe_opening_hours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafes.OpeningHours', verbose_name='Часы работы кафе'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='cafe_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafes.Owner', verbose_name='Владелец кафе'),
        ),
    ]
