# Generated by Django 2.0.6 on 2018-06-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='cafe_menu',
            field=models.ManyToManyField(blank=True, related_name='opetests', to='cafes.Item'),
        ),
    ]
