# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='cafe_name',
            field=models.CharField(default=' ', max_length=1000, verbose_name='Название кафе'),
        ),
    ]
