# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-13 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0002_cafe_cafe_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('opening_hours_id', models.AutoField(primary_key=True, serialize=False)),
                ('opening_time', models.DateField(verbose_name='Время открытия')),
                ('closing_time', models.DateField(verbose_name='Время закрытия')),
            ],
        ),
        migrations.AlterField(
            model_name='cafe',
            name='cafe_media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafes.Media', verbose_name='Фотографии кафе'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='cafe_rating',
            field=models.FloatField(verbose_name='Рейтинг кафе'),
        ),
    ]
