# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0003_auto_20180613_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='icon',
            field=models.ImageField(max_length=1000, upload_to='', verbose_name='Иконка кафе'),
        ),
        migrations.AlterField(
            model_name='media',
            name='photos',
            field=models.ImageField(max_length=1000, upload_to='', verbose_name='Картинки кафе'),
        ),
    ]
