# Generated by Django 2.0.6 on 2018-07-11 11:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0004_auto_20180630_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 11, 11, 57, 57, 844611, tzinfo=utc), verbose_name='Дата добавления'),
        ),
    ]
