# Generated by Django 2.0.6 on 2018-07-14 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0005_cafe_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления'),
        ),
    ]
