# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0006_auto_20180627_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='cafe_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cafes.Media', verbose_name='Фотографии кафе'),
        ),
    ]
