# Generated by Django 2.0.6 on 2018-07-15 15:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0007_auto_20180714_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 15, 5, 1, 17292, tzinfo=utc), verbose_name='Дата добавления'),
        ),
    ]
