# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0007_auto_20180627_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeMedia',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False)),
                ('icon', models.ImageField(max_length=1000, upload_to='', verbose_name='Иконка кафе')),
                ('photos', models.ImageField(max_length=1000, upload_to='', verbose_name='Картинки кафе')),
                ('cafe_id', models.IntegerField(verbose_name='ID кафе')),
            ],
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='cafe_media',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
