# Generated by Django 2.0.6 on 2018-07-15 20:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0008_auto_20180715_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 20, 8, 4, 436257, tzinfo=utc), verbose_name='Дата добавления'),
        ),
    ]
