# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0008_auto_20180627_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='cafe_opening_hours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafes.OpeningHours', verbose_name='Часы работы кафе'),
        ),
        migrations.AlterField(
            model_name='cafemedia',
            name='icon',
            field=models.ImageField(upload_to='', verbose_name='Иконка кафе'),
        ),
        migrations.AlterField(
            model_name='cafemedia',
            name='photos',
            field=models.ImageField(upload_to='', verbose_name='Картинки кафе'),
        ),
    ]
